// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE9UG5h1kA98QNbl015PvHW8TPQhyXgJk',
    appId: '1:102771446009:web:a536b645dc707d60a4d228',
    messagingSenderId: '102771446009',
    projectId: 'flutter-start-point',
    authDomain: 'flutter-start-point.firebaseapp.com',
    storageBucket: 'flutter-start-point.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3OZbE2npO-N6G_meYr7fv0SlP_N1llrQ',
    appId: '1:102771446009:android:c24744ef2499ad1ea4d228',
    messagingSenderId: '102771446009',
    projectId: 'flutter-start-point',
    storageBucket: 'flutter-start-point.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLUHuylg-GpcoHh8HJ3EmTJFWAr68voaU',
    appId: '1:102771446009:ios:b35ab3e2fb37cd93a4d228',
    messagingSenderId: '102771446009',
    projectId: 'flutter-start-point',
    storageBucket: 'flutter-start-point.appspot.com',
    iosBundleId: 'com.example.flutterStartPointApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLUHuylg-GpcoHh8HJ3EmTJFWAr68voaU',
    appId: '1:102771446009:ios:db8fc316a153bf22a4d228',
    messagingSenderId: '102771446009',
    projectId: 'flutter-start-point',
    storageBucket: 'flutter-start-point.appspot.com',
    iosBundleId: 'com.example.flutterStartPointApplication.RunnerTests',
  );
}
